
server:
  port: 8092

mybatis:
  mapper-locations: classpath:mappers/*.xml
  typeAliasesPackage: com.sharding.table.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  shardingsphere:
    datasource:
      names: demo                                        # ???????????????????
      demo:
        type: com.alibaba.druid.pool.DruidDataSource            # Druid???
        url: jdbc:mysql://127.0.0.1:3306/course_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC                  # ??demo?url
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 12345678
    sharding:
      tables:
        course:
          actual-data-nodes: demo.course_$->{1..2}
          table-strategy:
            inline:
              sharding-column: cid
              algorithm-expression: demo.course_$->{cid%2 + 1}
    props:
      sql:
        show:
          true                                                  # ??sql
